package smthinthewayy.Service;

public enum Permission {
  CREATE,
  READ_ALL_QUOTES,
  UPDATE_ALL_QUOTES,
  UPDATE_CLASSMATES_QUOTES,
  UPDATE_ONLY_MY_QUOTES,
  DELETE_ALL_QUOTES,
  DELETE_CLASSMATES_QUOTES,
  DELETE_ONLY_MY_QUOTES
}
